spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/postgres
    username: user
    password: 123123

balance-tracker:
  pre-jpa-liquibase:
    contexts: local
  post-jpa-liquibase:
    contexts: local
